name: Plots
main: me.benphelps.Plots.Plots
version: 0.0.1
commands:
  plots:
    description: Shows the version of Plots.
    usage: /<command>
    permission: plots.help
  plotsHelp:
    description: Shows Plots help.
    usage: /<command> help
    permission: plots.help
  plotsNew:
    description: Create a new plot.
    usage: /<command> new
    permission: plots.manage.new