name: Plots
main: me.benphelps.Plots.Plots
version: 0.0.1
commands:
  new:
    description: Create a new plot.
    usage: /<command> new
    permission: plots.manage
    permission-message: You don't have management permissions.